### ISSUE TITLE
Solicitud -  Tutorial Basico Linux

### ISSUE THREAD

**Issue by EduardoSergio** [nestortechtips/solicitudes#1]
Arquitectura: NA
Sistema Operativo: Ubuntu 14.04
Tecnología/Plataforma: Linea de Comandos
Descripción Breve de la solicitud: Me gustaría leer sobre la linea de comandos de Linux, quiero practicar como moverme y manipular archivos en las carpetas usando mi terminal.

**Comment by nVertoletik** [comment]
El tutorial será publicado en 3 semanas (2da semana de diciembre) debido a la carga de trabajo de esta temporada.
La publicación hablará sobre los temas de:

- Crear/Eliminar archivos y carpetas
- Navegar el sistema de archivos de Linux
- Permisos de usuario para realizar modificaciones en los archivos/carpetas.

Si estás de acuerdo en este temario, cerraré el issue.

**Comment by nVertoletik** [comment]
La publicación se encuentra lista.

Puedes acceder a ella utilizando el siguiente link.

https://nestortechtips.online/comandos-basicos-de-linux/
